<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Avatar' => '头像',
    'Coins' => '金币',
    'Credits' => '经验值',
    'Fans' => '粉丝',
    'Follow will be updated to remind' => '关注后将获得更新提醒',
    'Followed' => '已关注',
    'Follower' => '关注',
    'Gender' => '性别',
    'His Answer' => '他的回答',
    'His Articles' => '他的文章',
    'His Codes' => '他的代码',
    'His Coin' => '他的金币',
    'His Collect' => '他的收藏',
    'His Credit' => '他的经验',
    'His Followed' => '他的关注',
    'His Follower' => '他的粉丝',
    'His Notes' => '他的笔记',
    'His Page' => '他的主页',
    'His Questions' => '他的提问',
    'His Streams' => '他的直播',
    'I\'m Following' => '我的关注',
    'Joined on {0, date}' => '于 {0, date} 注册',
    'Latest Activities' => '最近动态',
    'Message' => '发私信',
    'My' => '我',
    'My Answers' => '我的回答',
    'My Articles' => '我的文章',
    'My Codes' => '我的代码',
    'My Coin' => '我的金币',
    'My Credit' => '我的积分',
    'My Favorites' => '我的收藏',
    'My Follower' => '我的粉丝',
    'My Notes' => '我的笔记',
    'My Page' => '我的主页',
    'My Questions' => '我的提问',
    'My Streams' => '我的直播',
    'Send message to' => '发送短信给',
    '{n, plural, =0{No visitors} =1{One visitor} other{# visitors}}' => '{n, plural, =0{暂无访客} =1{1个访客} other{# 访客}}',
    '{who} Page' => '{who}的主页',
];
